---
title: "index.Rmd"
author: "Liaqat Ali"
date: "9/14/2020"
output: html_document
bibliography: [data/references.bib]
Site: EvoGenomics-Course (https://liaqata.github.io/EvoGenomics-Course/)
Description: This contains html files for the course repository for Evolutionarey Genomics and Bioinformatics
---

## Labs 
This is my web site!

  [This is my Lab-1](Lab_1.html) : Introduction to R and Reproducible Research
  
  [This is my Lab-2](Lab_2.html) : git, GitHub and Rstudio projects
  
  [Lab-3A](Lab-3A.Liaqat.html)   :Data Wrangling
                                 
  [Lab-3B](Lab-3B.html)
  
  [Lab-4](Lab_4.html)           :Data Wrangling and graphing Covid-19 reporting data (Part 1)
  
  [Lab_5]()                     :   (Part 2)         
  
  [Lab_6](Lab_6.html)           : Data Maps and Interactive Graphs from the Covid-19 reporting data
  
  [Lab_7](Lab_7.html)           : RNA-Seq workflow: gene-level exploratoryanalysis and differential expression
  
  [Lab_7x](Lab_7x.html)
  
  [Lab_8]()                     Sequence Alignment, Phylogenetic Analysis and Tree Visualization
  
  [Lab_9](Lab_9.html)           : Programming in R- Regular Expressions
  
  [Lab_9A](Lab_9x.html)         : Programming in R-Control Structures and Functions
  
  [ Lab_10](Lab_10.html)        : Pupulation genomics based on high throughput sequencing (HTS)
  
  
 
 
 
 
  [References]
  []
  
  
  
  
  
   
   

[]
[]




---
