---
title: "Lab_3B"
author: "Liaqat Ali"
date: "9/14/2020"
output: html_document
---


library(tidyverse)
library("tidyverse")
library(dplyr)


```{r}
library(tidyverse)
library(dplyr)
```

```{r, eval= FALSE}
 download.file(url = "https://ndownloader.figshare.com/files/2292169",
              destfile = "data/portal_data_joined.csv")

```

```{r}
surveys <- read.csv("data/portal_data_joined.csv")
```

```{r}
str(surveys)
```
```{r, eval=FALSE}
View(surveys)
```


```{r}
select(surveys, -record_id, -species_id)
```

```{r}

filter(surveys, year == 1995)
```

```{r}
surveys2  <- filter(surveys, weight < 5)
surveys_sm1 <- select(surveys2, species_id, sex, weight)
```



```{r}
surveys %>%
    filter(year < 1995) %>%
    select(year, sex, weight)
```

```{r}
surveys %>%
    mutate(weight_kg = weight / 1000,
           weight_1b = weight_kg * 2.2)
```
```{r}
surveys %>%
  mutate ( weight_kg = weight /1000,
  weight_1b = weight_kg * 2.2)
```


```{r}
surveys_hindfoot_cm <- surveys %>%
    filter(!is.na(hindfoot_length)) %>%
    mutate(hindfoot_cm = hindfoot_length / 10) %>%
    filter(hindfoot_cm < 3) %>%
    select(species_id, hindfoot_cm)
```





```{r}
surveys %>%
    count(plot_type) 
```

```{r}
surveys_hindfoot_cm <- surveys %>%
  filter(!is.na(hindfoot_length)) %>%
  mutate(hindfoot_cm = hindfoot_length / 10) %>%
  filter(hindfoot_cm < 3) %>%
  select(species_id, hindfoot_cm) 
```

```{r}
surveys %>%
  group_by(sex) %>%
  summarize(mean_weight = mean(weight, na.rm = TRUE))
```
```{r}
surveys %>%
group_by(sex, species_id) %>%
summarize(mean_weight = mean(weight, na.rm = TRUE)) %>%
tail(10)
```


```{r}
surveys %>%
    filter(!is.na(weight)) %>%
    group_by(year) %>%
    filter(weight == max(weight)) %>%
    select(year, genus, species, weight) %>%
    arrange(year)
```

```{r}
surveys %>%
  filter (!is.na(weight)) %>%
  group_by(sex, species_id) %>%
  summarize(mean_weight = mean(weight)) %>%
  print (n = 15)
```

```{r}
surveys %>%
  filter(!is.na(weight)) %>%
  group_by(sex, species_id) %>%
  summarize(mean_weight = mean(weight),
            min_weight = min(weight)) %>%
  arrange(min_weight)
```
```{r}
surveys %>%
filter(is.na(weight)) %>%
group_by(sex, species_id)  %>%
summarize(mean_weight = mean (weight),
    min_weight = min(weight)) %>%
    arrange(desc(mean_weight))
```
```{r}
surveys %>%
count(sex)
```
```{r}
surveys %>%
group_by(sex) %>%
summarise(count = n())
```
```{r}
surveys %>%
count(sex, sort = TRUE)
```

```{r}
surveys %>%
  count(plot_type)
```
```{r}
surveys %>%
filter(!is.na(hindfoot_length)) %>%
group_by(species_id) %>%
summarize(
    mean_hindfoot_length = mean(hindfoot_length),
    min_hindfoot_length = min(hindfoot_length),
    max_hindfoot_length = max(hindfoot_length),
    n = n()
)
```

```{r}
surveys %>%
  filter(is.na(weight)) %>%
  group_by(year) %>%
  filter(weight == max(weight)) %>%
  select(year, genus, species, weight) %>%
  arrange(year)
```

```{r}
str(surveys)
```

library(dplyr)

### Challenge


```{r, eval=FALSE}
surveys_spread_genera %>%
  gather("year", "n_genera",-plot_id)
```


```{r,}
surveys_long <- surveys %>%
  gather("measurement", "value", hindfoot_length, weight)

```

```{r}
surveys_complete <- surveys %>%
  filter(!is.na(weight),
         !is.na(hindfoot_length),
         !is.na(sex))
```

```{r}
## Extaract the most common species_id
species_counts <- surveys_complete %>%
  count(species_id) %>%
  filter(n >= 50)

## Only keep the most common species
surveys_complete <- surveys_complete %>%
    filter(species_id %in% species_counts$species_id)
dim(surveys_complete)
```


```{r}
write_csv(surveys_complete, path = "data/surveys_complete.csv")
```





