---
title: "Lab_9"
author: "Liaqat Ali"
date: "11/1/2020"
output: html_document
---


```{r}
library(stringr)
library(tidyverse)
```

```{r}
x <- c("apple", "banana", "pear")
str_view(x, "an")
```

```{r}
str_view(x, ".a.")
```

```{r}
# To create the regular expression, we need \\
dot <- "\\."

# But the expression itself only contains one:
writeLines(dot)
```

```{r}
# And this tells R to look for an explicit .
x <- c("abc", "a.c", "bef")
str_view(x, "a\\.c")
```

```{r}
x <- "a\\b"
writeLines(x)
```

```{r}
str_view(x, "\\\\")
```

```{r}
### 14.3.1.1 Exercises
#Explain why each of these strings don’t match a \: "\", "\\", "\\\"

#"/": This will escape the next character in the R string.
##"\\": This will resolve to \ in the regular expression, which will escape the next character in the regular expression.
###"\\\": The first two backslashes will resolve to a literal backslash in the regular expression, the third will escape the next character. So in the regular expression, this will escape some escaped character.
```

```{r}
str_view("\"'\\", "\"'\\\\", match = TRUE)
```


```{r}
str_view(c(".a.b.c", ".a.b", "....."), c("\\..\\..\\.."), match = TRUE)
```


```{r}
x <- c("apple", "banana", "pear")
str_view(x, "^a")
```

```{r}
str_view(x, "a$")
```


```{r}
x <- c("apple pie", "apple", "apple cake")
str_view(x, "apple")
```


```{r}
str_view(x, "^apple$")
```

```{r}
### 14.3.2.1 Exercises
str_view(c("$^$", "ab$^$sfas"), "^\\$\\^\\$$", match = TRUE)
```

```{r}
str_view(stringr::words, "^y", match = TRUE)
```


```{r}
str_view(stringr::words, "x$", match = TRUE)
```

```{r}
str_view(stringr::words, "^...$", match = TRUE)
```

```{r}
str_view(stringr::words, ".......", match = TRUE)
```

```{r}
x <- c("abc", "a.c", "a*c", "a c")
str_view(x, "a[.]c")
```


```{r}
str_view(x, ".[*]c")
```

```{r}
str_view(x, "a[ ]")
```

```{r}
x <- c("grey", "gray")
str_view(x, "gr(e|a)y")
```

```{r}
### Exercise 14.3.3.1
# Words that starts with vowels
str_subset(stringr::words, "^[aeiou]")

```

```{r}
str_subset(stringr::words, "[aeiou]", negate=TRUE)
#> [1] "by"  "dry" "fly" "mrs" "try" "why"
```

```{r}
str_view(stringr::words, "[aeiou]", match=FALSE)
```

```{r}
str_subset(stringr::words, "[^e]ed$")

```

```{r}
str_subset(c("ed", stringr::words), "(^|[^e])ed$")

```


```{r}
str_subset(stringr::words, "i(ng|se)$")
```


```{r}
length(str_subset(stringr::words, "(cei|[^c]ie)"))

```

```{r}
length(str_subset(stringr::words, "(cie|[^c]ei)"))

```


```{r}
str_view(stringr::words, "q[^u]", match = TRUE)
```

```{r}
x <- c("123-456-7890", "(123)456-7890", "(123) 456-7890", "1235-2351")
str_view(x, "\\d\\d\\d-\\d\\d\\d-\\d\\d\\d\\d")
```

```{r}
str_view(x, "[0-9][0-9][0-9]-[0-9][0-9][0-9]-[0-9][0-9][0-9][0-9]")
```

```{r}
str_view(x, "\\(\\d\\d\\d\\)\\s*\\d\\d\\d-\\d\\d\\d\\d")
```

```{r}
str_view(x, "\\([0-9][0-9][0-9]\\)[ ]*[0-9][0-9][0-9]-[0-9][0-9][0-9][0-9]")
```


```{r}
str_view(x, "\\d{3}-\\d{3}-\\d{4}")
```

```{r}
str_view(x, "\\(\\d{3}\\)\\s*\\d{3}-\\d{4}")
```

```{r}

```

```{r}
length(str_subset(stringr::words, "(cei|[^c]ie)"))

```









