---
title: "Lab-5"
author: "Liaqat Ali"
date: "9/27/2020"
output: html_document
---

```{r}
library(tidyverse)
library(lubridate)
```


```{r}
reports_03_13_2020 <-   read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-13-2020.csv")) %>%
  rename(Country.Region = "Country/Region", Province.State = "Province/State")
```


```{r}
Confirmed_State_03_13_2020 <-   read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-13-2020.csv")) %>%

  rename(Country.Region = "Country/Region", Province.state = "Province/State") %>%
  filter (Country.Region == "US") %>% 
  group_by(Country.Region, Province.state) %>%
 summarise(Confirmed = sum(Confirmed)) 
 
```
```{r}
str(Confirmed_State_03_13_2020)
```

```{r}
Confirmed_State_9_13 <-   read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/09-13-2020.csv")) %>% 
  filter (Country_Region == "US") %>% 
  group_by(Province_State, Country_Region) %>% 
  summarise(Confirmed = sum(Confirmed)) 
```

```{r}
str(Confirmed_State_9_13)
```

```{r}
setdiff(Confirmed_State_9_13$Province_State, Confirmed_State_03_13_2020$Province.state)
```
```{r}
Confirmed_State_9_13 <- Confirmed_State_9_13 %>%
filter(Province_State != "Recovered")
```


```{r}
merge.data.frame(Confirmed_State_03_13_2020, Confirmed_State_9_13, by.x = "Province.state", by.y = "Province_State")
```








```{r}
time_series_confirmed <- read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv")) %>%
  rename(Province_State = "Province/State", Country_Region = "Country/Region")

```

```{r}
 download.file(url="https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv", 
               destfile = "data/time_series_covid19_confirmed_global.csv")
```

```{r}
time_series_confirmed <- read_csv("data/time_series_covid19_confirmed_global.csv")%>%
  rename(Province_State = "Province/State", Country_Region = "Country/Region")
```

```{r}
head(time_series_confirmed)
```



```{r}
time_series_confirmed_long <- time_series_confirmed %>% 
               pivot_longer(-c(Province_State, Country_Region, Lat, Long),
                            names_to = "Date", values_to = "Confirmed") 

```



```{r}
head(time_series_confirmed_long)

```



```{r}
 download.file(url="https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv", 
               destfile = "data/time_series_covid19_deaths_global.csv")
```



```{r}
time_series_deaths <- read_csv("data/time_series_covid19_deaths_global.csv")%>%
  rename(Province_State = "Province/State", Country_Region = "Country/Region")
```


```{r}
time_series_deaths_long <- time_series_deaths %>% 
               pivot_longer(-c(Province_State, Country_Region, Lat, Long),
                            names_to = "Date", values_to = "Deaths") 
head(time_series_deaths_long)
```

```{r}
time_series_confirmed_long <- time_series_confirmed_long %>% 
  unite(Key, Province_State, Country_Region, Date, sep = ".", remove = FALSE)
head(time_series_confirmed_long)
```

```{r}
time_series_deaths_long <- time_series_deaths_long %>% 
  unite(Key, Province_State, Country_Region, Date, sep = ".") %>% 
  select(Key, Deaths)

```


```{r}
time_series_long_joined <- full_join(time_series_confirmed_long,
              time_series_deaths_long, by = c("Key")) %>% 
              select(-Key)
head(time_series_long_joined)
```

```{r}
which(is.na(time_series_long_joined$Confirmed))
```



```{r}
which(is.na(time_series_long_joined$Deaths))

```

```{r}
library(lubridate)
```

```{r}
time_series_long_joined$Date <- mdy(time_series_long_joined$Date)
```


```{r}
time_series_long_joined_counts <- time_series_long_joined %>% 
  pivot_longer(-c(Province_State, Country_Region, Lat, Long, Date),
               names_to = "Report_Type", values_to = "Counts")
head(time_series_long_joined_counts)
```



```{r}
time_series_long_joined %>%
  group_by(Country_Region,Date) %>% 
  summarise_at(c("Confirmed", "Deaths"), sum) %>% 
  filter (Country_Region == "US") %>% 
    ggplot(aes(x = Date,  y = Deaths)) + 
    geom_point() +
    geom_line() +
    ggtitle("US COVID-19 Deaths")
```


```{r}
time_series_long_joined %>% 
  group_by(Country_Region,Date) %>% 
  summarise_at(c("Confirmed", "Deaths"), sum) %>% 
  filter (Country_Region %in% c("China","Pakistan", 
                              "Italy","Inda", "New Zealand", "Nigeria", "US")) %>% 
    ggplot(aes(x = Date,  y = Deaths)) + 
    geom_point() +
    geom_line() +
    ggtitle("COVID-19 Deaths") +
    facet_wrap(~Country_Region, ncol=2, scales="free_y")

```

```{r}
time_series_long_joined %>% 
    group_by(Country_Region,Date) %>% 
    summarise_at(c("Confirmed", "Deaths"), sum) %>% 
    filter (Country_Region %in% c("China","Pakistan", 
                              "Italy","Inda", "New Zealand", "Nigeria", "US")) %>% 
    ggplot(aes(x = Date,  y = Deaths, color = Country_Region)) + 
    geom_point() +
    geom_line() +
    ggtitle("COVID-19 Deaths")
```



```{r}
time_series_long_joined_counts %>% 
  group_by(Country_Region, Report_Type, Date) %>% 
  summarise(Counts = sum(Counts)) %>% 
  filter (Country_Region == "US") %>% 
    ggplot(aes(x = Date,  y = log2(Counts), fill = Report_Type, color = Report_Type)) + 
    geom_point() +
    geom_line() +
    ggtitle("US COVID-19 Cases")
```


```{r}
reports_03_13_2020 %>% 
  filter (Country.Region == "US") %>% 
  ggplot(aes(x = Deaths,  y = reorder(Province.State, Deaths))) + 
    geom_bar(stat = 'identity') +
    ggtitle("Death cases for each State in US") +
    ylab("Country/Region") +
    xlab("Deaths Cases")
```


```{r}
time_series_long_joined %>% 
  group_by(Country_Region,Date) %>% 
  summarise_at(c("Confirmed", "Deaths"), sum) %>% 
  filter (Country_Region == "US") %>% 
    ggplot(aes(x = Date,  y = Deaths)) +
  geom_bar(stat = 'identity') +
    geom_point() +
    geom_line() +
    ggtitle("US COVID-19 Deaths")
```

```{r}
time_series_long_joined_counts %>% 
  group_by(Country_Region, Report_Type, Date) %>% 
  summarise(Counts = sum(Counts)) %>% 
    ggplot(aes(x = Date,  y = log2(Counts), fill = Report_Type, color = Report_Type)) +
    geom_point( ) +
    geom_line() +
    ggtitle("Total number of Confirmed Cases vs Deaths per day Worldwide")
```



```{r}
time_series_long_joined %>% 
  group_by(Province_State, 9/1/20) %>%
  filter (Country_Region == "US") %>%
  summarise(Deaths = sum(Deaths)) %>% 
  arrange(desc(Deaths)) %>%  
    ggplot(aes(x = 9/1/20,  y = Deaths)) + 
    geom_point(color = "Black") +
    geom_line( color = "Red") +
    ggtitle( "Total deaths cases in one day")
```




```{r}
time_series_long_joined %>%  
  group_by(Country_Region) %>% 
  summarise(Deaths = sum(Deaths)) %>% 
  arrange(desc(Deaths)) %>% 
  slice(1:10) %>% 
  ggplot(aes(x = Deaths,  y = reorder(Country_Region, Deaths))) + 
    geom_bar(stat = 'identity') +
    ggtitle("The 10 countries with the most reported COV19-related deaths") +
    ylab("Country/Region") +
    xlab("Deaths")
```

```{r}
 time_series_long_joined %>%
  filter (Country_Region == "Canada") %>% 
  ggplot(aes(x = Deaths,  y = reorder(Province_State, Deaths))) + 
    geom_point() +
    ggtitle("Total Death Cases in the Canada") +
    ylab("Death Cases") +
    xlab("Country/Region")

```


