---
title: "Lab_8"
author: "Liaqat Ali"
date: "10/25/2020"
output: html_document
---


```{r}
BiocManager::install("ggtree")
```


```{r}
library(tidyverse)
```


```{r}
library(ggtree)
```
```{r}
library(treeio)
```

```{r}
library(ggimage)
```


```{r}

tree <- read.tree("data/tree_newick.nwk")
ggplot(tree) + geom_tree() + theme_tree()

```

```{r}
ggtree(tree) + geom_treescale()
```

```{r}
ggtree(tree, branch.length = "none", color = "Purple", size = 2, linetype = 3)
```

```{r}
ggtree(tree, layout= "circular")
```
`
```{r}
ggtree(tree) +
  geom_nodepoint(alpha = 0.5, color = "orange", size = 3) +
  geom_tippoint(color = "red", shape = "diamond") +
  geom_tiplab(color = "red") +
  ggtitle("Phylogenetic tree with new aesthetics")
```

```{r}
ggtree(tree) + geom_text(aes(label = node), hjust = -.2)
```



```{r}
ggtree(tree) + geom_tiplab()
```


```{r}
ggtree(tree) +
  geom_cladelabel(node = 17, label = "Some randome clade", color = "red")
```


```{r}
ggtree(tree) +
  geom_tiplab() +
  geom_cladelabel(node = 17, label = "Some random clade",
                  color = "red2", offset = .8)
```

```{r}
ggtree(tree) + 
  geom_tiplab() +
  geom_cladelabel(node = 17, label = "Some random clade",
                  color = "Green2", offset = .8) +
  geom_cladelabel(node = 21, label = "A different clade",
                  color = "Purple", offset = .8)
```


```{r}
ggtree(tree) + 
  geom_tiplab() + 
  geom_cladelabel(node=17, label="Some random clade", 
                  color="Green", offset=.8, align=TRUE) + 
  geom_cladelabel(node=21, label="A different clade", 
                  color="Purple", offset=.8, align=TRUE) + 
  theme_tree2() + 
  xlim(0, 70) + 
  theme_tree()
```

```{r}
ggtree(tree) + 
  geom_tiplab() + 
  geom_hilight(node=17, fill="Yellow") + 
  geom_hilight(node=21, fill="light blue")
```

```{r}
ggtree(tree) +
  geom_tiplab() +
  geom_taxalink("E", "H", color = "Green") +
  geom_taxalink("C", "G", color  = "Red", curvature = -.9)
```

```{r}
ggtree(tree) +
  geom_tiplab() +
  geom_cladelabel(node = 19, label = "Superclade 17", color = "Green", offset = .8, align = TRUE) +
   geom_hilight(node = 19, fill = "Gold") +
  geom_hilight(node = 21, fill = "Purple") +
  geom_taxalink("C", "E", curvature = .3, linetype = 2) +
  geom_taxalink("G", "J", curvature = .4, linetype = 2) +
  theme_tree2() +
  ggtitle("Tree for Exercise 3")
```


```{r}
newtree <- read.tree("data/tree_newick.nwk")
newtree
```





```{r}
ggtree(newtree) +
  geom_text(aes(label = node), hjust = -.3)
  geom_hilight(node=34, fill="gold", extend = 0.5) 
```




```{r}
ggtree(newtree, layout = "circular") +
  geom_tiplab() +
  geom_hilight(node = 19, fill = "gold") +
  geom_hilight(node = 24, fill = "blue3") +
  geom_hilight(node = 22, fill = "purple", extend = -.8)
   
```




 